pub const BOOT_LOGS: &[&str] = &[
    "=== Zrub Boot Loader ===",
    "Checking CPU... OK",
    "Loading Stage2... OK",
    "======| Zrub Boot Loader |======",
    "  [1] Load Zinux",
    "  [2] Reboot PC",
    "Use 1/2 or arrows, Enter=select",
    "Loading kernel... OK",
    "Loading disk... OK",
    "Setting video... OK",
    "",
    "SERIALTEST:",
    "done",
    "",
    "Zinux debug checking",
    "  [.] memory... OK",
    "  [.] system... OK",
    "  [.] keyboard... OK",
    "  [.] mouse... OK",
    "  [.] IRQ... OK",
    "  [.] PIT... OK",
    "  [.] disk... OK (RAM disk, 512KB)",
    "  [.] FAT16... OK",
    "  [.] API... OK",
    "  [.] ZXE... OK",
    "  [.] shell... OK",
    "",
    "========================================",
    "     Welcome to dolbaeb simulator!",
    "        the best game in 2026",
    "========================================",
    "",
    "",
];
